import type {
  AdminApprovalQueueResponse,
  AdminAuditResponse,
  AdminBuilderAgentStudioQuotaPolicy,
  AdminConnectedAppsResponse,
  AdminConnectorRegistryResponse,
  AdminHardwareResponse,
  AdminInferenceDashboard,
  AdminLibreChatAgentPosture,
  AdminOverviewResponse,
  AdminPolicyViolationsResponse,
  AdminPureModeResponse,
  AdminSettingsResponse,
  AdminTeamOverviewResponse,
  AgenticAdapterDiagnosticsResponse,
  AgenticRuntimeHistoryResponse,
  AgenticStatusResponse,
  HermesAccessResponse,
  OpenClawAccessResponse,
} from "@llm-machines/contracts"

export const adminTeamOverview: AdminTeamOverviewResponse = {
  breakGlass: {
    eligibleAdmins: [],
    selectedAdminId: null,
    updatedAt: null,
    updatedBy: null,
  },
  generatedAt: "2026-05-29T12:00:00.000Z",
  groups: [
    {
      id: "everyone",
      keycloakHref: null,
      memberCount: 0,
      name: "Everyone",
      unlockCount: 0,
      virtual: true,
    },
  ],
  members: [],
  scim: {
    detail: "Keycloak admin API is not configured for Team management.",
    keycloakHref: null,
    lastSyncAt: null,
    provider: null,
    sourceStatus: "not_configured",
    status: "not_configured",
  },
  serviceStatus: "not_configured",
  sourceStatus: "not_configured",
}

export const adminSettings: AdminSettingsResponse = {
  generatedAt: "2026-05-29T12:00:00.000Z",
  sourceStatus: "not_configured",
  organization: {
    organizationName: "LLM Machines",
    defaultLanguage: "en",
    fullLogo: null,
    iconLogo: null,
    updatedAt: null,
    updatedBy: null,
  },
  urlPolicyRules: [],
  reachability: [
    {
      id: "web",
      label: "Web/Console",
      status: "ok",
      detail: "Console web process is serving the Settings page.",
      owningSection: "settings",
      lastCheckedAt: "2026-05-29T12:00:00.000Z",
    },
    {
      id: "bff",
      label: "BFF/API",
      status: "not_configured",
      detail: "Console BFF reachability is not configured in fixture mode.",
      owningSection: "settings",
      lastCheckedAt: null,
    },
    {
      id: "postgres",
      label: "Postgres",
      status: "not_configured",
      detail: "Database reachability is reported by the BFF when configured.",
      owningSection: "settings",
      lastCheckedAt: null,
    },
    {
      id: "redis",
      label: "Redis",
      status: "not_configured",
      detail: "Redis reachability is reported by the BFF when configured.",
      owningSection: "settings",
      lastCheckedAt: null,
    },
    {
      id: "minio",
      label: "MinIO",
      status: "not_configured",
      detail:
        "Object storage reachability is reported by the BFF when configured.",
      owningSection: "settings",
      lastCheckedAt: null,
    },
    {
      id: "keycloak",
      label: "Keycloak",
      status: "not_configured",
      detail: "Authentication management lives in Team, not Settings.",
      owningSection: "team",
      lastCheckedAt: null,
    },
    {
      id: "litellm",
      label: "LiteLLM",
      status: "not_configured",
      detail: "Model routing and model updates live in Inference.",
      owningSection: "inference",
      lastCheckedAt: null,
    },
    {
      id: "librechat",
      label: "LibreChat",
      status: "not_configured",
      detail: "core-appliance application updates live in Applications.",
      owningSection: "applications",
      lastCheckedAt: null,
    },
    {
      id: "grafana",
      label: "Grafana",
      status: "not_configured",
      detail: "Hardware graphs live in Hardware.",
      owningSection: "hardware",
      lastCheckedAt: null,
    },
    {
      id: "agentic_adapter",
      label: "Agentic adapter",
      status: "not_configured",
      detail: "Agentic egress URL policy integration is unfinished.",
      owningSection: "applications",
      lastCheckedAt: null,
    },
  ],
  license: {
    sourceStatus: "not_configured",
    subscriptionState: "not_configured",
    supportState: "License daemon not connected.",
    applianceId: null,
    certificateExpiresAt: null,
    lastEntitlementCheckAt: null,
    offlineMode: true,
    telemetryOptIn: false,
    allowedUpdateChannels: [],
  },
  systemUpdate: {
    sourceStatus: "not_configured",
    status: "not_configured",
    updateActionEnabled: false,
    detail:
      "System update backend for Proxmox, OS, drivers, and firmware is not implemented yet.",
    availableVersion: null,
    expectedDowntime: null,
    affectedComponents: [],
  },
  privacy: {
    telemetryEnabled: false,
    privacyPolicyHref: "/privacy",
    dataResidencyStatement:
      "Customer prompts, documents, outputs, and logs stay on the deployed appliance by default.",
    telemetryDescription:
      "Telemetry is off by default and can be enabled only after reviewing the exact payload preview.",
    telemetryPayloadPreview: {
      applianceId: null,
      installedVersion: null,
      updateAgentVersion: null,
      lastUpdateCheck: null,
      lastAppliedUpdate: null,
      subscriptionStateSeenByAppliance: "not_configured",
    },
    updatedAt: null,
    updatedBy: null,
  },
}

export const adminBuilderAgentStudioQuotaPolicy: AdminBuilderAgentStudioQuotaPolicy =
  {
    generatedAt: "2026-05-21T12:00:00.000Z",
    sourceStatus: "not_configured",
    period: "daily",
    timezone: "UTC",
    source: "environment",
    enforced: false,
    runLimit: null,
    tokenLimit: null,
    updatedAt: null,
    updatedBy: null,
  }

export const adminAgenticStatus: AgenticStatusResponse = {
  runtimes: [
    {
      runtime: "openclaw",
      profile: "openclaw-restricted",
      configured: true,
      healthy: true,
      baseUrl: "https://litellm.example.test/v1/chat/completions",
      detail: "HTTP 200",
    },
    {
      runtime: "hermes",
      profile: "hermes-restricted",
      configured: true,
      healthy: true,
      baseUrl: "https://runtime-a.example.test",
      detail: "HTTP 200",
    },
  ],
}

export const adminOpenClawAccess: OpenClawAccessResponse = {
  runtime: "openclaw",
  profile: "openclaw-restricted",
  configured: true,
  dashboardUrl: "https://litellm.example.test/",
  tokenRequired: true,
}

export const adminHermesAccess: HermesAccessResponse = {
  runtime: "hermes",
  profile: "hermes-restricted",
  configured: true,
  chatCompletionsProxyPath: "/api/admin/agentic/hermes/v1/chat/completions",
  tokenRequired: true,
}

export const adminAgenticAdapterDiagnostics: AgenticAdapterDiagnosticsResponse =
  {
    configured: true,
    healthy: true,
    service: "agentic-adapter",
    status: "ok",
    baseUrl: "https://runtime-b.example.test",
    applyEnabled: false,
    detail: "HTTP 200",
  }

export const adminAgenticHistory: AgenticRuntimeHistoryResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  windowHours: 24,
  samples: [
    {
      runtime: "openclaw",
      profile: "openclaw-restricted",
      configured: true,
      healthy: true,
      baseUrl: "https://litellm.example.test/v1/chat/completions",
      detail: "HTTP 200",
      capturedAt: "2026-05-21T11:55:00.000Z",
    },
    {
      runtime: "hermes",
      profile: "hermes-restricted",
      configured: true,
      healthy: true,
      baseUrl: "https://runtime-a.example.test",
      detail: "HTTP 200",
      capturedAt: "2026-05-21T11:55:00.000Z",
    },
  ],
  slos: [
    {
      runtime: "openclaw",
      profile: "openclaw-restricted",
      windowHours: 24,
      status: "healthy",
      sampleCount: 1,
      configuredSamples: 1,
      healthySamples: 1,
      uptimePercent: 100,
      lastHealthyAt: "2026-05-21T11:55:00.000Z",
      lastUnhealthyAt: null,
    },
    {
      runtime: "hermes",
      profile: "hermes-restricted",
      windowHours: 24,
      status: "healthy",
      sampleCount: 1,
      configuredSamples: 1,
      healthySamples: 1,
      uptimePercent: 100,
      lastHealthyAt: "2026-05-21T11:55:00.000Z",
      lastUnhealthyAt: null,
    },
  ],
}

export const adminApprovalQueue: AdminApprovalQueueResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  query: null,
  sourceStatus: "ok",
  pendingCount: 1,
  items: [
    {
      id: "88888888-8888-4888-8888-888888888888",
      resourceId: "99999999-9999-4999-8999-999999999999",
      resourceName: "Internal Docs Corpus",
      resourceType: "rag_corpus",
      description: "Submitted internal documentation corpus awaiting review.",
      ownerId: "builder-1",
      ownerName: "Builder One",
      submittedVersion: "v0.2",
      submittedAt: "2026-05-21T08:45:00.000Z",
      updatedAt: "2026-05-21T08:45:00.000Z",
      reviewHref: "/builder/resources/99999999-9999-4999-8999-999999999999",
      auditHref: "#audit-log-deferred",
    },
  ],
}

export const adminConnectorRegistry: AdminConnectorRegistryResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  query: null,
  sourceStatus: "ok",
  summary: {
    totalCount: 1,
    approvedCount: 1,
    pendingCount: 0,
    blockedCount: 0,
    secretsRequiredCount: 0,
    t2T3Count: 1,
  },
  items: [
    {
      id: "internal-docs",
      displayName: "Internal Docs",
      description:
        "Read-only connector for appliance-local documentation search.",
      version: "0.1.0",
      sourceRef: "llm-machines/catalog/internal-docs@0.1.0",
      checksum: "sha256:internal-docs-placeholder",
      license: "LLM Machines",
      supportTier: "t2",
      maintainer: "LLM Machines",
      vettingStatus: "approved_read_only",
      requiredScopes: ["docs:read"],
      allowedEndpoints: ["docs.example.test:443"],
      readWrite: "read_only",
      dataClasses: ["documentation"],
      auditEvents: ["connector.docs.search", "connector.docs.read"],
      runtimeProfile: "managed-tool-proxy",
      secretsRequired: [],
      lastReviewedAt: "2026-05-20T00:00:00.000Z",
      sourceStatus: "ok",
      posture: "approved",
      effectiveVettingStatus: "approved_read_only",
      localDecision: null,
      runtimeSetup: {
        activeEgress: [],
        detail: "Managed local connector is approved and ready.",
        missingEgress: [],
        missingSecrets: [],
        runnable: true,
        setupHref: "/applications",
        status: "ready",
      },
      reviewHref: "/resources/mcp_connector/internal-docs",
      auditHref: "#audit-log-deferred",
    },
  ],
}

export const adminMcpServerDetail = {
  accessGroups: [],
  accessLevel: "read_only",
  auditHref: "#audit-log-deferred",
  authMode: "none",
  bearerTokenSecretRef: null,
  chatCommand: "@docs-mcp",
  createdAt: "2026-05-29T12:00:00.000Z",
  description: "Documentation MCP server.",
  endpointUrl: "https://mcp.example.test/rpc",
  id: "docs-mcp",
  name: "Docs MCP",
  status: "enabled",
  stdioCommand: null,
  supportTier: "t3",
  transport: "url",
  updatedAt: "2026-05-29T12:00:00.000Z",
} as const

export const adminConnectedApps: AdminConnectedAppsResponse = {
  apps: [
    {
      allowedModels: ["llama-3.1-8b-instruct", "qwen2.5-14b-instruct"],
      auditHref: "#audit-log-deferred",
      createdAt: "2026-05-30T09:00:00.000Z",
      description: "Claims intake workflow connected through the BFF gateway.",
      detailHref: "/applications/apps/connected-app-claims-portal",
      environments: [
        {
          authMethods: ["api_key"],
          clientId: "llmm-app-connected-app-claims-portal-staging",
          credentialIssuedAt: "2026-05-30T09:00:00.000Z",
          environment: "staging",
          keyPrefix: "llmm_t4_claims",
          lastUsedAt: "2026-05-31T09:30:00.000Z",
          lastTestedAt: "2026-05-30T09:12:00.000Z",
          primaryAuthMethod: "api_key",
          productionReady: false,
          testStatus: "passed",
        },
      ],
      id: "connected-app-claims-portal",
      name: "Claims Portal",
      ownerGroup: "Everyone",
      rateLimitRpm: 120,
      status: "enabled",
      tokenBudget7d: 1_000_000,
      updatedAt: "2026-05-30T09:12:00.000Z",
      usage: {
        failures7d: 2,
        lastUsedAt: "2026-05-31T09:30:00.000Z",
        requests7d: 842,
        tokens7d: 284_000,
      },
    },
    {
      allowedModels: ["llama-3.1-70b-instruct"],
      auditHref: "#audit-log-deferred",
      createdAt: "2026-05-29T14:00:00.000Z",
      description: "Support desk assistant for approved production traffic.",
      detailHref: "/applications/apps/connected-app-support-desk",
      environments: [
        {
          authMethods: ["api_key"],
          clientId: "llmm-app-connected-app-support-desk-staging",
          credentialIssuedAt: "2026-05-29T14:00:00.000Z",
          environment: "staging",
          keyPrefix: "llmm_t4_support",
          lastUsedAt: "2026-05-31T08:40:00.000Z",
          lastTestedAt: "2026-05-29T14:20:00.000Z",
          primaryAuthMethod: "api_key",
          productionReady: true,
          testStatus: "passed",
        },
        {
          authMethods: ["oauth_client_credentials"],
          clientId: "llmm-app-connected-app-support-desk-production",
          credentialIssuedAt: "2026-05-29T14:30:00.000Z",
          environment: "production",
          keyPrefix: null,
          lastUsedAt: null,
          lastTestedAt: "2026-05-29T14:42:00.000Z",
          primaryAuthMethod: "oauth_client_credentials",
          productionReady: true,
          testStatus: "passed",
        },
      ],
      id: "connected-app-support-desk",
      name: "Support Desk",
      ownerGroup: "Operators",
      rateLimitRpm: 60,
      status: "enabled",
      tokenBudget7d: 500_000,
      updatedAt: "2026-05-29T14:42:00.000Z",
      usage: {
        failures7d: 0,
        lastUsedAt: "2026-05-31T08:40:00.000Z",
        requests7d: 314,
        tokens7d: 96_200,
      },
    },
  ],
  generatedAt: "2026-05-31T10:00:00.000Z",
  sourceStatus: "ok",
}

export const adminLibreChatAgentPosture: AdminLibreChatAgentPosture = {
  generatedAt: "2026-05-24T12:00:00.000Z",
  sourceStatus: "ok",
  enabled: true,
  memoryEnabled: false,
  creatorPolicy: "builders_admins",
  modelEndpoint: "bff_litellm",
  mcpMode: "catalog_only",
  mcpGateway: {
    sourceStatus: "ok",
    runnableCount: 1,
    blockedCount: 0,
    exposedConnectorIds: ["internal-docs"],
  },
  mirroredAgents: [],
  recentAuditHref: "#audit-log-deferred",
}

export const adminOverview: AdminOverviewResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  tiles: [
    {
      id: "ops",
      title: "LLM operations",
      summary:
        "Gateway usage, model inventory, virtual keys, and governed model updates live in Console Inference.",
      href: "/inference",
      sourceStatus: "degraded",
      updatedAt: "2026-05-21T12:00:00.000Z",
      metrics: [
        {
          id: "requests",
          label: "Requests",
          value: "1,280",
          detail: "Hub usage fallback",
          tone: "neutral",
        },
        {
          id: "tokens",
          label: "Tokens",
          value: "824,000",
          detail: "Hub usage fallback",
          tone: "neutral",
        },
        {
          id: "top-model",
          label: "Top model",
          value: "qwen3-35b-local",
          detail: null,
          tone: "neutral",
        },
        {
          id: "p95-latency",
          label: "p95 latency",
          value: "Pending",
          detail: "LiteLLM API",
          tone: "neutral",
        },
        {
          id: "top-user",
          label: "Top user",
          value: "Pending",
          detail: "LiteLLM API",
          tone: "neutral",
        },
      ],
    },
    {
      id: "health",
      title: "Health",
      summary:
        "Operational drilldowns are linked; Prometheus/Grafana summary federation is not configured for this BFF.",
      href: "https://grafana.example.test/d/llmm-infra-overview/llm-machines-infrastructure-overview",
      sourceStatus: "not_configured",
      updatedAt: "2026-05-21T12:00:00.000Z",
      metrics: [
        {
          id: "gpu",
          label: "GPU utilization",
          value: "Pending",
          detail: "Prometheus API",
          tone: "neutral",
        },
        {
          id: "alerts",
          label: "Alerts",
          value: "0",
          detail: "No BFF alert feed",
          tone: "good",
        },
        {
          id: "uptime",
          label: "Targets up",
          value: "Pending",
          detail: "Prometheus API",
          tone: "neutral",
        },
        {
          id: "storage",
          label: "Max disk used",
          value: "Pending",
          detail: "Prometheus API",
          tone: "neutral",
        },
      ],
    },
    {
      id: "governance",
      title: "Governance",
      summary:
        "Governance DB reports 0 policy violations in 24h and Pure Mode inactive.",
      href: "/settings",
      sourceStatus: "degraded",
      updatedAt: "2026-05-21T12:00:00.000Z",
      metrics: [
        {
          id: "pending-submissions",
          label: "Submissions",
          value: "1",
          detail: "Awaiting review",
          tone: "warning",
        },
        {
          id: "blocked-connectors",
          label: "Blocked connectors",
          value: "0",
          detail: "Only internal-docs is exposed",
          tone: "good",
        },
        {
          id: "policy-violations",
          label: "Policy violations",
          value: "0",
          detail: "0 critical in 24h",
          tone: "good",
        },
        {
          id: "pure-mode",
          label: "Pure Mode",
          value: "Inactive",
          detail: "No activation recorded",
          tone: "good",
        },
      ],
    },
    {
      id: "activity",
      title: "Activity",
      summary:
        "Recent Console audit rows are available; external audit sources remain future federators.",
      href: "#audit-log-deferred",
      sourceStatus: "ok",
      updatedAt: "2026-05-21T12:00:00.000Z",
      metrics: [
        {
          id: "events",
          label: "Audit events",
          value: "3",
          detail: "Latest 10",
          tone: "neutral",
        },
        {
          id: "last-action",
          label: "Last action",
          value: "admin.builder_resource.approve",
          detail: "admin-1",
          tone: "neutral",
        },
        {
          id: "auth-denials",
          label: "Auth denials",
          value: "0",
          detail: "Latest 10",
          tone: "good",
        },
      ],
    },
  ],
  activityEvents: [
    {
      id: "audit-admin-approve",
      actorId: "admin-1",
      action: "admin.builder_resource.approve",
      targetType: "builder.resources",
      targetId: "66666666-6666-4666-8666-666666666666",
      severity: "info",
      href: "#audit-log-deferred",
      createdAt: "2026-05-21T11:45:00.000Z",
    },
    {
      id: "audit-builder-submit",
      actorId: "builder-1",
      action: "builder.resource.submit",
      targetType: "builder.resources",
      targetId: "77777777-7777-4777-8777-777777777777",
      severity: "info",
      href: "#audit-log-deferred",
      createdAt: "2026-05-21T11:30:00.000Z",
    },
    {
      id: "audit-auth-denied",
      actorId: "consumer-1",
      action: "auth.denied",
      targetType: "route",
      targetId: "/api/admin/overview",
      severity: "warning",
      href: "#audit-log-deferred",
      createdAt: "2026-05-21T11:15:00.000Z",
    },
  ],
}

const hardwarePoints = [
  "2026-05-21T06:00:00.000Z",
  "2026-05-21T09:00:00.000Z",
  "2026-05-21T12:00:00.000Z",
]

export const adminHardware: AdminHardwareResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  range: "6h",
  step: "180s",
  selectedHost: "all",
  availableHosts: ["core-appliance", "compute-node-a", "compute-node-b"],
  sourceStatus: "ok",
  summary: "Prometheus is returning all 7 curated hardware signals.",
  grafanaUrl:
    "https://grafana.example.test/d/llmm-infra-overview/llm-machines-infrastructure-overview",
  alertmanagerUrl: null,
  charts: [
    {
      id: "cpu_utilization",
      title: "CPU utilization",
      description: "Average non-idle CPU time by host.",
      chartType: "area",
      unit: "percent",
      promql:
        '100 * (1 - avg by (host) (rate(node_cpu_seconds_total{job="node",mode="idle"}[5m])))',
      sourceStatus: "ok",
      emptyMessage: "No node CPU utilization metrics are available.",
      grafanaUrl: null,
      thresholds: [
        { label: "High", severity: "warning", value: 85, unit: "percent" },
        { label: "Critical", severity: "critical", value: 95, unit: "percent" },
      ],
      series: [
        {
          id: "cpu_utilization-1",
          label: "core-appliance",
          host: "core-appliance",
          device: null,
          direction: null,
          metricSource: "node_exporter",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [31, 42, 38][index] ?? 0,
          })),
        },
      ],
    },
    {
      id: "gpu_temperature",
      title: "GPU temperature",
      description: "GPU package temperature from DCGM or nvidia-smi fallback.",
      chartType: "line",
      unit: "celsius",
      promql: "DCGM_FI_DEV_GPU_TEMP or llmm_nvidia_gpu_temperature_celsius",
      sourceStatus: "ok",
      emptyMessage: "No GPU temperature metrics are available.",
      grafanaUrl: null,
      thresholds: [
        { label: "Warning", severity: "warning", value: 85, unit: "celsius" },
      ],
      series: [
        {
          id: "gpu_temperature-1",
          label: "compute-node-b / GPU 0",
          host: "compute-node-b",
          device: "0",
          direction: null,
          metricSource: "nvidia-smi",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [61, 66, 64][index] ?? 0,
          })),
        },
      ],
    },
    {
      id: "gpu_utilization",
      title: "GPU utilization",
      description: "GPU core utilization from DCGM or nvidia-smi fallback.",
      chartType: "area",
      unit: "percent",
      promql: "DCGM_FI_DEV_GPU_UTIL or llmm_nvidia_gpu_utilization_percent",
      sourceStatus: "ok",
      emptyMessage: "No GPU utilization metrics are available.",
      grafanaUrl: null,
      thresholds: [
        {
          label: "Sustained high",
          severity: "warning",
          value: 90,
          unit: "percent",
        },
      ],
      series: [
        {
          id: "gpu_utilization-1",
          label: "compute-node-b / GPU 0",
          host: "compute-node-b",
          device: "0",
          direction: null,
          metricSource: "nvidia-smi",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [47, 72, 59][index] ?? 0,
          })),
        },
      ],
    },
    {
      id: "ram_usage",
      title: "RAM usage",
      description: "Memory pressure by host using MemAvailable over MemTotal.",
      chartType: "area",
      unit: "percent",
      promql:
        '100 * (1 - (node_memory_MemAvailable_bytes{job="node"} / node_memory_MemTotal_bytes{job="node"}))',
      sourceStatus: "ok",
      emptyMessage: "No node memory metrics are available.",
      grafanaUrl: null,
      thresholds: [
        { label: "High", severity: "warning", value: 85, unit: "percent" },
        { label: "Critical", severity: "critical", value: 95, unit: "percent" },
      ],
      series: [
        {
          id: "ram_usage-1",
          label: "core-appliance",
          host: "core-appliance",
          device: null,
          direction: null,
          metricSource: "node_exporter",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [54, 58, 57][index] ?? 0,
          })),
        },
      ],
    },
    {
      id: "filesystem_usage",
      title: "Filesystem usage",
      description: "Latest filesystem use by host and mountpoint.",
      chartType: "bar",
      unit: "percent",
      promql:
        '100 * (1 - (node_filesystem_avail_bytes{job="node"} / node_filesystem_size_bytes{job="node"}))',
      sourceStatus: "ok",
      emptyMessage: "No filesystem capacity metrics are available.",
      grafanaUrl: null,
      thresholds: [
        { label: "High", severity: "warning", value: 85, unit: "percent" },
        { label: "Critical", severity: "critical", value: 95, unit: "percent" },
      ],
      series: [
        {
          id: "filesystem_usage-1",
          label: "core-appliance / /",
          host: "core-appliance",
          device: "/",
          direction: null,
          metricSource: "node_exporter",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [63, 64, 64][index] ?? 0,
          })),
        },
      ],
    },
    {
      id: "power_draw",
      title: "Power draw",
      description: "Live chassis power draw for compute-node-a from IPMI DCMI.",
      chartType: "area",
      unit: "watt",
      promql: 'ipmi_dcmi_power_consumption_watts{host="compute-node-a"}',
      sourceStatus: "ok",
      emptyMessage: "No IPMI DCMI power draw metrics are available.",
      grafanaUrl: null,
      thresholds: [],
      series: [
        {
          id: "power_draw-1",
          label: "compute-node-a",
          host: "compute-node-a",
          device: null,
          direction: null,
          metricSource: "ipmi_exporter",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [101, 108, 105][index] ?? 0,
          })),
        },
      ],
    },
    {
      id: "network_throughput",
      title: "Network throughput",
      description: "Receive and transmit rate by host and network device.",
      chartType: "line",
      unit: "bytes_per_second",
      promql:
        'rate(node_network_receive_bytes_total{job="node"}[5m]) or rate(node_network_transmit_bytes_total{job="node"}[5m])',
      sourceStatus: "ok",
      emptyMessage: "No network throughput metrics are available.",
      grafanaUrl: null,
      thresholds: [],
      series: [
        {
          id: "network_throughput-1",
          label: "core-appliance / eth0 / RX",
          host: "core-appliance",
          device: "eth0",
          direction: "RX",
          metricSource: "node_exporter",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [1250000, 1820000, 1510000][index] ?? 0,
          })),
        },
        {
          id: "network_throughput-2",
          label: "core-appliance / eth0 / TX",
          host: "core-appliance",
          device: "eth0",
          direction: "TX",
          metricSource: "node_exporter",
          points: hardwarePoints.map((timestamp, index) => ({
            timestamp,
            value: [820000, 940000, 910000][index] ?? 0,
          })),
        },
      ],
    },
  ],
  activeAlerts: [],
}

const inferencePoints = [
  "2026-05-21T00:00:00.000Z",
  "2026-05-22T00:00:00.000Z",
  "2026-05-23T00:00:00.000Z",
  "2026-05-24T00:00:00.000Z",
  "2026-05-25T00:00:00.000Z",
]

export const adminInference: AdminInferenceDashboard = {
  generatedAt: "2026-05-25T12:00:00.000Z",
  liteLlmUrl: "https://litellm.example.test/ui/",
  modelUpdate: {
    affectedModels: ["qwen3:32b", "gemma3:27b"],
    availableVersion: "2026.05.3",
    currentVersion: "2026.05.1",
    detail:
      "Curated on-appliance model bundle update with Croatian retrieval prompt improvements.",
    estimatedDowntime: "About 4 minutes while LiteLLM reloads model routing.",
    releaseNotes:
      "Improves Croatian policy answers, tightens JSON output defaults, and refreshes model cost metadata.",
    status: "available",
    updateActionEnabled: true,
  },
  modelUsage: [
    {
      lastUsedAt: "2026-05-25T11:40:00.000Z",
      model: "qwen3:32b",
      requests: 826,
      spendUsd: 0,
      tokens: 512000,
    },
    {
      lastUsedAt: "2026-05-25T11:10:00.000Z",
      model: "gemma3:27b",
      requests: 318,
      spendUsd: 0,
      tokens: 244000,
    },
    {
      lastUsedAt: "2026-05-24T16:25:00.000Z",
      model: "llama3.1:8b",
      requests: 136,
      spendUsd: 0,
      tokens: 68000,
    },
  ],
  models: [
    {
      contextWindow: 32768,
      id: "qwen3:32b",
      mode: "chat",
      name: "qwen3:32b",
      outputCostPerMillionTokens: 0,
      provider: "ollama",
      sourceStatus: "ok",
    },
    {
      contextWindow: 16384,
      id: "gemma3:27b",
      mode: "chat",
      name: "gemma3:27b",
      outputCostPerMillionTokens: 0,
      provider: "ollama",
      sourceStatus: "ok",
    },
    {
      contextWindow: 8192,
      id: "llama3.1:8b",
      mode: "chat",
      name: "llama3.1:8b",
      outputCostPerMillionTokens: 0,
      provider: "ollama",
      sourceStatus: "ok",
    },
  ],
  range: "30d",
  sourceStatus: "ok",
  summary:
    "LiteLLM is returning usage, model inventory, and redacted virtual-key metadata.",
  totals: {
    requests: 1280,
    tokens: 824000,
  },
  usagePoints: inferencePoints.map((timestamp, index) => ({
    requests: [184, 231, 217, 296, 352][index] ?? 0,
    timestamp,
    tokens: [102000, 143000, 129000, 191000, 259000][index] ?? 0,
  })),
  virtualKeys: [
    {
      alias: "Agentic runtime",
      budgetUsd: null,
      expiresAt: null,
      id: "vk_analytics_runtime",
      lastUsedAt: "2026-05-25T11:40:00.000Z",
      models: ["qwen3:32b", "gemma3:27b"],
      owner: "Operations",
      spendUsd: 0,
      status: "active",
      team: "Everyone",
    },
    {
      alias: "Builder studio",
      budgetUsd: 100,
      expiresAt: "2026-12-31T00:00:00.000Z",
      id: "vk_builder_studio",
      lastUsedAt: "2026-05-24T18:12:00.000Z",
      models: ["qwen3:32b"],
      owner: "Builder group",
      spendUsd: 0,
      status: "active",
      team: "Builders",
    },
  ],
}

export const adminAudit: AdminAuditResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  query: null,
  selectedEventId: null,
  sourceStatus: "degraded",
  sources: [
    {
      id: "console",
      label: "Console audit",
      sourceStatus: "ok",
    },
    {
      id: "external-audit",
      label: "External audit sources",
      sourceStatus: "not_configured",
    },
  ],
  events: [
    {
      id: "audit-admin-approve",
      actorId: "admin-1",
      action: "admin.builder_resource.approve",
      targetType: "builder.resources",
      targetId: "66666666-6666-4666-8666-666666666666",
      reason: null,
      severity: "info",
      metadata: [
        {
          label: "authMode",
          value: "service-forwarded",
        },
      ],
      href: "#audit-log-deferred",
      createdAt: "2026-05-21T11:45:00.000Z",
    },
    {
      id: "audit-builder-submit",
      actorId: "builder-1",
      action: "builder.resource.submit",
      targetType: "builder.resources",
      targetId: "77777777-7777-4777-8777-777777777777",
      reason: null,
      severity: "info",
      metadata: [],
      href: "#audit-log-deferred",
      createdAt: "2026-05-21T11:30:00.000Z",
    },
    {
      id: "audit-auth-denied",
      actorId: "consumer-1",
      action: "auth.denied",
      targetType: "route",
      targetId: "/api/admin/overview",
      reason: "insufficient_persona",
      severity: "warning",
      metadata: [
        {
          label: "requiredPersona",
          value: "admin",
        },
      ],
      href: "#audit-log-deferred",
      createdAt: "2026-05-21T11:15:00.000Z",
    },
  ],
}

export const adminPolicyViolations: AdminPolicyViolationsResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  query: null,
  sourceStatus: "ok",
  window: "24h",
  totalCount: 0,
  criticalCount: 0,
  warningCount: 0,
  violations: [],
}

export const adminPureMode: AdminPureModeResponse = {
  generatedAt: "2026-05-21T12:00:00.000Z",
  sourceStatus: "ok",
  active: false,
  reason: null,
  activatedBy: null,
  activatedAt: null,
  deactivatedAt: null,
  affectedComponents: [],
  updatedAt: "2026-05-21T12:00:00.000Z",
  control: {
    enabled: false,
    reason:
      "Pure Mode transitions require the governance store before they can be persisted.",
  },
  recentEvents: [],
}
