import type {
  BuilderAgentStudio,
  BuilderResource,
  BuilderSubmission,
  BuilderTemplate,
} from "@llm-machines/contracts"

export const builderTemplates: BuilderTemplate[] = [
  {
    id: "template-summary-agent",
    type: "agent",
    name: "Summary Agent",
    description: "A single-step agent for clean summaries over pasted context.",
    category: "Agent",
    version: "0.1.0",
    supportTier: "t1",
    tags: ["agent", "summary"],
    samplePrompts: [
      "Summarize this incident report for an executive.",
      "Turn these meeting notes into owners and next steps.",
    ],
    href: "/builder/templates/template-summary-agent",
    forkHref: "/builder/templates/template-summary-agent/fork",
  },
  {
    id: "template-pr-reviewer",
    type: "agent",
    name: "PR Reviewer",
    description: "Reviews diffs for risk, tests, and rollout notes.",
    category: "Agent",
    version: "0.1.0",
    supportTier: "t1",
    tags: ["agent", "code-review"],
    samplePrompts: [
      "Review this patch for auth regressions.",
      "Find missing tests in this diff.",
    ],
    href: "/builder/templates/template-pr-reviewer",
    forkHref: "/builder/templates/template-pr-reviewer/fork",
  },
  {
    id: "template-standup",
    type: "agent",
    name: "Standup Digest",
    description: "Starter template for team status summaries.",
    category: "Agent",
    version: "0.1.0",
    supportTier: "t1",
    tags: ["agent", "team", "digest"],
    samplePrompts: [
      "Summarize yesterday's standup updates into blockers and owners.",
      "Create a concise team digest from these status notes.",
    ],
    href: "/builder/templates/template-standup",
    forkHref: "/builder/templates/template-standup/fork",
  },
  {
    id: "template-internal-docs-corpus",
    type: "rag_corpus",
    name: "Internal Docs Corpus",
    description: "Starter corpus for governed internal documentation search.",
    category: "Knowledge",
    version: "0.1.0",
    supportTier: "t1",
    tags: ["knowledge", "rag"],
    samplePrompts: [
      "Answer using only the approved onboarding docs.",
      "Find the source paragraph for this policy answer.",
    ],
    href: "/builder/templates/template-internal-docs-corpus",
    forkHref: "/builder/templates/template-internal-docs-corpus/fork",
  },
  {
    id: "template-daily-report-workflow",
    type: "workflow",
    name: "Daily Report Workflow",
    description:
      "Placeholder workflow template for daily summaries once the runtime is selected.",
    category: "Workflow",
    version: "0.1.0",
    supportTier: "t2",
    tags: ["workflow", "reporting"],
    samplePrompts: [
      "Generate yesterday's operations digest.",
      "Prepare a daily release readiness note.",
    ],
    href: "/builder/templates/template-daily-report-workflow",
    forkHref: "/builder/templates/template-daily-report-workflow/fork",
  },
  {
    id: "template-react-app",
    type: "custom_app",
    name: "React App Minimal",
    description:
      "Minimal custom app scaffold for the future sandbox runtime path.",
    category: "Custom App",
    version: "0.1.0",
    supportTier: "t3",
    tags: ["app", "react"],
    samplePrompts: [
      "Create a compact dashboard over approved API data.",
      "Build a form-backed utility for a support team.",
    ],
    href: "/builder/templates/template-react-app",
    forkHref: "/builder/templates/template-react-app/fork",
  },
]

export const builderResources: BuilderResource[] = [
  {
    id: "66666666-6666-4666-8666-666666666666",
    type: "agent",
    name: "Summary Agent",
    description: "Draft summary agent built from the starter template.",
    ownerId: "builder-1",
    ownerName: "Builder One",
    state: "draft",
    templateId: "template-summary-agent",
    currentVersion: {
      id: "77777777-7777-4777-8777-777777777777",
      semver: "v0.1",
      createdAt: "2026-05-21T08:00:00.000Z",
    },
    updatedAt: "2026-05-21T08:20:00.000Z",
    href: "/builder/resources/66666666-6666-4666-8666-666666666666",
    editorHref: "/builder/agents/66666666-6666-4666-8666-666666666666",
  },
  {
    id: "99999999-9999-4999-8999-999999999999",
    type: "rag_corpus",
    name: "Internal Docs Corpus",
    description: "Submitted internal documentation corpus awaiting review.",
    ownerId: "builder-1",
    ownerName: "Builder One",
    state: "submitted",
    templateId: "template-internal-docs-corpus",
    currentVersion: {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      semver: "v0.2",
      createdAt: "2026-05-21T08:10:00.000Z",
    },
    updatedAt: "2026-05-21T08:45:00.000Z",
    href: "/builder/resources/99999999-9999-4999-8999-999999999999",
    editorHref: "/builder/knowledge/99999999-9999-4999-8999-999999999999",
  },
]

export const builderAgentStudios: BuilderAgentStudio[] = [
  {
    resource: builderResources[0],
    config: {
      resourceId: "66666666-6666-4666-8666-666666666666",
      model: "qwen3-35b-local",
      sandboxProfile: "openclaw-restricted",
      systemPrompt:
        "You are a concise summarization agent for appliance-local work context.",
      instructions:
        "Summarize the provided context into the most important facts, decisions, risks, and next actions. Keep the response concise.",
      temperature: 0.2,
      maxOutputTokens: 1024,
      tools: [],
      sampleInput: "Summarize this incident report for an executive.",
      updatedAt: "2026-05-21T08:20:00.000Z",
    },
    editable: true,
    testable: true,
    quota: {
      period: "daily",
      timezone: "UTC",
      status: "unlimited",
      enforced: false,
      usedRuns: 1,
      runLimit: null,
      remainingRuns: null,
      usedTokens: 0,
      tokenLimit: null,
      remainingTokens: null,
      resetsAt: "2026-05-22T00:00:00.000Z",
    },
    recentTestRuns: [
      {
        id: "11111111-1111-4111-8111-111111111111",
        resourceId: "66666666-6666-4666-8666-666666666666",
        input: "Summarize this incident report for an executive.",
        output:
          "The incident affected one internal workflow. The immediate next step is to validate the runtime route and attach the audit note.",
        source: "local_preview",
        status: "succeeded",
        model: "qwen3-35b-local",
        sandboxProfile: "openclaw-restricted",
        durationMs: 184,
        runtimeTraceId: "trace-builder-fixture-1",
        finishReason: null,
        promptTokens: null,
        completionTokens: null,
        totalTokens: null,
        errorDetail: null,
        trace: [
          {
            at: "2026-05-21T08:25:00.000Z",
            label: "Quota preflight",
            status: "succeeded",
            detail: "Daily quota is not enforced.",
          },
          {
            at: "2026-05-21T08:25:00.000Z",
            label: "Runtime dispatch",
            status: "succeeded",
            detail: "Local preview completed.",
          },
        ],
        toolCalls: [],
        createdAt: "2026-05-21T08:25:00.000Z",
      },
    ],
  },
]

export const builderSubmissions: BuilderSubmission[] = [
  {
    id: "88888888-8888-4888-8888-888888888888",
    resourceId: "99999999-9999-4999-8999-999999999999",
    resourceName: "Internal Docs Corpus",
    resourceType: "rag_corpus",
    submittedVersion: "v0.2",
    state: "submitted",
    adminComment: null,
    submittedAt: "2026-05-21T08:45:00.000Z",
    decidedAt: null,
    href: "/builder/submissions/88888888-8888-4888-8888-888888888888",
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
    resourceId: "66666666-6666-4666-8666-666666666666",
    resourceName: "Summary Agent",
    resourceType: "agent",
    submittedVersion: "v0.1",
    state: "rejected",
    adminComment: "Narrow the system prompt and add one test input.",
    submittedAt: "2026-05-20T12:00:00.000Z",
    decidedAt: "2026-05-20T13:15:00.000Z",
    href: "/builder/submissions/dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  },
]
