export const productCopy = {
  appName: "LLM Machines Console",
  metadata: {
    description: "Sovereign on-prem AI console",
  },
  pages: {
    home: {
      readiness: "Milestone 0 readiness is underway.",
    },
    hub: {
      title: "Hub",
      eyebrow: "Role-aware workbench",
      subtitle:
        "Chat, resources, notifications, usage, and work artifacts in one appliance workspace.",
      chatTitle: "Chat workspace",
      chatBody:
        "Ask the local model from Hub or jump into the mirrored LibreChat conversations below.",
      commandPlaceholder: "Search threads, agents, MCPs, tasks, policies",
      notifications: "Notifications",
      resources: "Resources",
      usage: "Usage",
      developerWorkbench: "Developer workbench",
      adminAttention: "Admin attention",
      builderStatus: "Builder status",
      activePersona: "Active persona",
      capabilities: "Capabilities",
      noElevatedCapabilities: "Standard Hub access",
      profile: "Profile",
      tasks: "Tasks",
      profileMenu: {
        triggerLabel: "Profile and capabilities",
      },
      navigation: {
        ariaLabel: "Hub navigation",
        chat: "Chat",
        home: "Home",
        resources: "Resources",
        tasks: "Tasks",
        usage: "Usage",
        profile: "Profile",
        builder: "Builder",
        admin: "Admin",
      },
      landmarks: {
        primaryNavigation: "Primary navigation",
        statusPanels: "Hub status panels",
      },
      chat: {
        badge: "LibreChat",
        promptHint: "Ask the local model or invoke @summary-agent",
        promptInputLabel: "Hub prompt",
        promptSubmit: "Send",
        promptResponseTitle: "Response",
        promptError:
          "The Hub prompt could not reach the local model path. Open the full chat workspace or retry after the BFF connection is healthy.",
        promptFixtureResponse: (input: string) =>
          `Local Hub preview received: "${input}". Connect the BFF to route this prompt to the appliance model path.`,
        openFullWorkspace: "Open LibreChat",
      },
      recentChats: {
        title: "Latest chats",
        description:
          "Recent LibreChat conversations mirrored into Hub for quick resume.",
        open: "Open in LibreChat",
        empty: "No recent chats are visible for this account.",
        model: "Model",
        resource: "Resource",
      },
      embeddedSurface: {
        externalRoute: "External route",
        notConfigured: "Not configured",
        openSurface: (title: string) => `Open ${title}`,
        secureFrame: "SSO bridge frame",
      },
      chatSurface: {
        eyebrow: "Conversation layer",
        title: "Chat",
        description:
          "LibreChat runs as the conversation engine inside the Hub. The surrounding shell keeps resources, artifacts, permissions, and notifications in one workspace.",
        contextTitle: "Workspace context",
        contextActionTitle: "Attachable context",
        contextBody:
          "Attach resources, corpora, tasks, and artifacts from the Hub. Slash-command parsing and access checks stay behind the BFF.",
      },
      builderSurface: {
        eyebrow: "Builder handoff",
        title: "Builder",
        description:
          "Resume drafts, submissions, test output, and artifacts from the Hub. Full authoring, versioning, and publishing remain in Builder.",
        statusTitle: "Build status",
        templatesTitle: "Starter templates",
        submissionsTitle: "Submissions",
        workbenchTitle: "Workbench sessions",
        resourcesTitle: "Owned and suggested resources",
        openTemplates: "Open templates",
        openSubmissions: "Open submissions",
        openTask: "Open task",
        openArtifact: "Open artifact",
        openResource: "Open resource",
        unavailableTitle: "Builder access unavailable",
        unavailableBody:
          "This route requires Builder capability. Hub access remains available for chat, resources, usage, and profile.",
      },
      builderTemplates: {
        eyebrow: "Template gallery",
        title: "Starter Templates",
        description:
          "Fork a governed starter kit into Builder. Runtime-heavy templates remain scaffolded until the matching runtime is selected.",
        openTemplate: "Open template",
        fork: "Fork template",
        forkName: "Fork name",
        samplePrompts: "Sample prompts",
      },
      builderSubmissions: {
        eyebrow: "Publishing pipeline",
        title: "Submissions",
        description:
          "Track submitted versions, admin decisions, and rejected work that needs another pass.",
        empty: "No submissions are visible for this Builder account.",
        adminComment: "Admin comment",
        submittedAt: "Submitted",
        decidedAt: "Decided",
      },
      builderResourceDetail: {
        eyebrow: "Builder resource",
        description:
          "Lifecycle controls for versioning, submission, and admin decisions. Agents open into the form-view Studio for prompt, model, and test work.",
        openAgentStudio: "Open Agent Studio",
        editorUnavailable: "Editor surface pending",
        currentVersion: "Current version",
        fromTemplate: "From template",
        lifecycleActions: "Lifecycle actions",
        cutVersion: "Cut version",
        semver: "Version tag",
        submit: "Submit for review",
        withdraw: "Withdraw submission",
        approve: "Approve",
        reject: "Reject",
        rejectionComment: "Rejection comment",
        awaitingReview: "Awaiting admin review",
        published:
          "Published resources are runnable from Hub after catalog exposure.",
        unversionedHelp:
          "Cut an explicit version before submitting this resource for review.",
        withdrawHelp:
          "Return this version to draft before an admin decision is made.",
        actionMessages: {
          forked: "Template forked into your Builder resources.",
          versioned: "Version cut and attached to the resource.",
          submitted: "Resource submitted for admin review.",
          withdrawn: "Submission withdrawn and returned to draft.",
          approved: "Submission approved and resource published.",
          rejected: "Submission rejected and returned to draft.",
          studioSaved: "Agent Studio draft saved.",
          studioReset: "Agent Studio draft reset to template defaults.",
          testRunsCleared: "Agent Studio test history cleared.",
          failed:
            "Lifecycle action failed. Check your role, resource state, and BFF configuration.",
        },
      },
      builderAgentStudio: {
        eyebrow: "Builder Agent Studio",
        title: "Agent Studio",
        description:
          "Tune the draft agent definition, model posture, and controlled test input before cutting the next version.",
        definition: "Agent definition",
        runtime: "Runtime posture",
        testTitle: "Test pane",
        model: "Model",
        sandboxProfile: "Sandbox profile",
        temperature: "Temperature",
        maxOutputTokens: "Max output tokens",
        systemPrompt: "System prompt",
        instructions: "Instructions",
        sampleInput: "Sample input",
        tools: "Allowed tools",
        toolsHelp: "One tool id per line or comma-separated.",
        save: "Save Studio draft",
        runTest: "Run test",
        streaming: "Streaming",
        testInput: "Test input",
        result: "Result",
        noTestYet: "No test run yet.",
        waitingForTokens: "Waiting for runtime output...",
        testHistory: "Test history",
        noTestHistory: "No recorded Studio tests yet.",
        status: "Status",
        duration: "Duration",
        finishReason: "Finish reason",
        runId: "Run ID",
        runtimeTraceId: "Runtime trace",
        tokens: "Tokens",
        trace: "Trace",
        toolCalls: "Tool calls",
        toolArguments: "Arguments",
        quotaTitle: "Daily test quota",
        quotaRuns: "Runs",
        quotaTokens: "Tokens",
        quotaResets: "Resets",
        quotaUnlimited: "Unlimited",
        quotaStatus: {
          unlimited: "Unlimited",
          ok: "Available",
          near_limit: "Near limit",
          exhausted: "Exhausted",
        },
        error: "Error",
        editableLocked:
          "This Studio is read-only because only the owning Builder can edit a draft agent.",
        source: "Source",
        updatedAt: "Config updated",
        cleanupTitle: "Cleanup controls",
        cleanupHelp:
          "These controls only affect the current draft Studio workspace.",
        resetDraft: "Reset Studio draft",
        clearTestRuns: "Clear test history",
        resetConfirmation: "RESET",
        clearConfirmation: "CLEAR",
        confirmationLabel: "Confirmation",
      },
      adminSurface: {
        eyebrow: "Admin command center",
        title: "Admin",
        description:
          "Triage stack health, approvals, policy issues, usage, and embedded drilldowns. Destructive actions stay in dedicated admin confirmation flows.",
        attentionTitle: "Attention summary",
        attentionItemsTitle: "Needs review",
        attentionItemCount: (count: number) => `${count} flagged`,
        overviewTitle: "Overview",
        overviewDescription:
          "Read-only federation across LLM operations, infrastructure health, governance, and audit activity.",
        tileOpen: "Open drilldown",
        updatedLabel: "Updated",
        activityTitle: "Recent activity",
        activityDescription:
          "Latest Console audit rows from the Admin read model.",
        emptyActivity: "No recent activity is visible.",
        connectedAppsTitle: "Connected apps",
        connectedAppsDescription:
          "Customer-owned apps route through the BFF gateway. Credential changes and production promotion stay in Applications.",
        connectedAppsOpen: "Open Applications",
        connectedAppsEmpty: "No connected apps have been issued yet.",
        sourceStatus: {
          ok: "Live",
          degraded: "Partial",
          unavailable: "Unavailable",
          not_configured: "Not configured",
        },
        usageTitle: "Organization usage",
        notificationsTitle: "Admin notifications",
        embedsTitle: "Operational drilldowns",
        critical: "Critical",
        warnings: "Warnings",
        unavailableTitle: "Admin access unavailable",
        unavailableBody:
          "This route requires Admin capability. Hub access remains available for the current persona.",
        embeddedSurfaces: {
          grafana:
            "Infrastructure drilldown for health, capacity, and appliance signals.",
          keycloak:
            "Identity administration drilldown. User and role changes remain audited admin work.",
          litellm:
            "Model gateway drilldown for provider health, model routing, and operational checks.",
        },
      },
      adminApprovals: {
        eyebrow: "Publishing review",
        title: "Approval queue",
        description:
          "Review submitted Builder resources before they become runnable from the Hub. Decisions use the existing audited publishing lifecycle.",
        searchLabel: "Search approvals",
        searchPlaceholder: "Resource, owner, type, version",
        searchButton: "Search",
        clearSearch: "Clear",
        generatedLabel: "Updated",
        summaryTitle: "Pending reviews",
        queueTitle: "Submitted resources",
        empty: "No Builder submissions are waiting for review.",
        review: "Review details",
        openAudit: "Open audit search",
        approve: "Approve",
        reject: "Reject",
        rejectionComment: "Rejection comment",
        rejectionPlaceholder: "What needs to change before publishing?",
        owner: "Owner",
        version: "Version",
        submitted: "Submitted",
        type: "Type",
        actionMessages: {
          approved: "Submission approved and published.",
          rejected: "Submission rejected and returned to draft.",
          failed:
            "Approval action failed. Check the current state and Admin role.",
        },
      },
      adminConnectorRegistry: {
        eyebrow: "Connector registry",
        title: "Registry",
        description:
          "Review MCP catalog posture before connectors can become runnable from the Hub. Local decisions are audited as appliance policy overlays on top of the signed catalog.",
        searchLabel: "Search registry",
        searchPlaceholder: "Connector, scope, endpoint, data class",
        searchButton: "Search",
        clearSearch: "Clear",
        generatedLabel: "Updated",
        summaryTitle: "Catalog posture",
        catalogTitle: "MCP connectors",
        empty: "No connectors match this filter.",
        total: "Total",
        approved: "Approved",
        pending: "Needs review",
        blocked: "Blocked",
        secretsRequired: "Secrets",
        t2T3: "T2/T3",
        review: "Review resource",
        openAudit: "Open audit search",
        readOnlyNotice:
          "Catalog metadata stays signed and immutable. Admin decisions below control local availability and still require runtime setup before a connector can run.",
        decisionNote: "Decision note",
        decisionPlaceholder:
          "Record the review basis: scope, endpoints, data class, source, and operational constraints.",
        reviewChecklistHint:
          "Approvals require every checklist item. Block and disable actions store the checked evidence but do not require all items.",
        reviewChecklistTitle: "Review checklist",
        runtimeSetupTitle: "Runtime setup",
        runtimeSetupAction: "Open setup gate",
        approveReadOnly: "Approve read-only",
        approveReadWrite: "Approve read/write",
        block: "Block",
        disable: "Disable",
        actionMessages: {
          approved_read_only: "Connector approved for read-only use.",
          approved_read_write: "Connector approved for read/write use.",
          blocked: "Connector blocked by local policy.",
          disabled: "Connector disabled by local policy.",
          failed:
            "Connector vetting action failed. Check the catalog posture, note, review checklist, and Admin role.",
        },
        checklist: {
          auditEventsReviewed: "Audit events reviewed",
          dataClassesReviewed: "Data classes reviewed",
          endpointsReviewed: "Endpoint allowlist reviewed",
          licenseReviewed: "License posture reviewed",
          runtimeSetupAcknowledged: "Runtime setup still required",
          scopesReviewed: "OAuth scopes reviewed",
          secretsPlanReviewed: "Secret handling plan reviewed",
          sourceIntegrityReviewed: "Source and checksum reviewed",
        },
        checklistNone: "No checklist evidence recorded.",
        runtimeSetupStatus: {
          blocked_by_policy: "Blocked by policy",
          missing_egress: "Missing egress",
          missing_secrets: "Missing secrets",
          needs_vetting: "Needs vetting",
          ready: "Runnable",
          unsupported_runtime: "Unsupported runtime",
        },
        labels: {
          allowedEndpoints: "Allowed endpoints",
          activeEgress: "Active egress",
          auditEvents: "Audit events",
          checksum: "Checksum",
          dataClasses: "Data classes",
          effectiveVettingStatus: "Effective vetting",
          lastReviewed: "Last reviewed",
          license: "License",
          localDecision: "Local decision",
          missingEgress: "Missing egress",
          missingSecrets: "Missing secrets",
          maintainer: "Maintainer",
          readWrite: "Read/write",
          requiredScopes: "Required scopes",
          runtimeProfile: "Runtime profile",
          secretsRequired: "Secrets required",
          sourceRef: "Source ref",
          supportTier: "Support tier",
          version: "Version",
          vettingStatus: "Vetting",
        },
        posture: {
          approved: "Approved",
          review_required: "Review required",
          blocked: "Blocked",
          disabled: "Disabled",
          deprecated: "Deprecated",
        },
      },
      adminLibreChatAgents: {
        eyebrow: "LibreChat workstation",
        title: "Native agents",
        description:
          "Inspect the native LibreChat agent posture while Console remains the governance, audit, and connector approval backplane.",
        generatedLabel: "Updated",
        workstationTitle: "Workstation posture",
        mcpTitle: "MCP gateway",
        mirroredTitle: "Mirrored agents",
        audit: "Open audit",
        enabled: "Enabled",
        disabled: "Disabled",
        memoryDeferred: "Memory deferred",
        creatorPolicyLabel: "Creator policy",
        creatorPolicy: "Builders and Admins create",
        modelEndpointLabel: "Model endpoint",
        modelEndpoint: "BFF and LiteLLM",
        mcpMode: "Catalog only",
        runnableConnectors: "Runnable connectors",
        blockedConnectors: "Blocked connectors",
        exposedConnectors: "Exposed connectors",
        emptyAgents:
          "No native LibreChat agent metadata has been mirrored yet.",
      },
      adminAgenticRuntime: {
        eyebrow: "Agentic runtime",
        title: "Runtime",
        description:
          "Inspect OpenClaw and Hermes posture for Hub agent execution, Builder Studio tests, and controlled runtime handoffs.",
        generatedLabel: "Updated",
        summaryTitle: "Runtime posture",
        historyTitle: "Runtime SLOs",
        historyDescription:
          "Availability is calculated from Admin runtime status snapshots in the selected history window.",
        accessTitle: "OpenClaw access",
        hermesAccessTitle: "Hermes access",
        adapterDiagnosticsTitle: "Adapter diagnostics",
        boundariesTitle: "Runtime boundaries",
        egressApprovalTitle: "Scoped egress approval",
        egressApprovalDescription:
          "Approve one outbound host and port for one restricted runtime profile.",
        connectorPrefillTitle: "Connector setup",
        connectorPrefillDescription:
          "This form was prefilled from the selected connector catalog metadata. Review it before applying.",
        readOnlyNotice:
          "Runtime toggles remain outside this page. Egress approvals run through the audited adapter boundary.",
        openDashboard: "Open dashboard",
        openDrilldown: "Open drilldown",
        configured: "Configured",
        notConfigured: "Not configured",
        healthy: "Healthy",
        partial: "Partial",
        offline: "Offline",
        tokenRequired: "Token required",
        applyEnabled: "Apply enabled",
        dryRun: "Dry run",
        egressUnavailable: "Adapter unavailable",
        egressSubmitApply: "Apply approval",
        egressSubmitDryRun: "Run dry run",
        egressHostPlaceholder: "api.github.com",
        egressReasonPlaceholder: "Why this destination is needed",
        labels: {
          access: "Access",
          accessMode: "Access mode",
          applyMode: "Apply mode",
          detail: "Probe",
          diagnostics: "Diagnostics",
          endpoint: "Endpoint",
          endpointHost: "Endpoint host",
          endpointPort: "Port",
          expiresAt: "Expires at",
          lastIssue: "Last issue",
          profile: "Profile",
          proxy: "Proxy",
          reason: "Reason",
          runtime: "Runtime",
          samples: "Samples",
          service: "Service",
          status: "Status",
          uptime: "Uptime",
          window: "Window",
        },
        accessModes: {
          readOnly: "Read-only",
          readWrite: "Read/write",
        },
        profiles: {
          hermesRestricted: "Hermes restricted",
          hermesTools: "Hermes tools",
          openclawRestricted: "OpenClaw restricted",
          openclawTools: "OpenClaw tools",
        },
        sloStatus: {
          healthy: "Healthy",
          degraded: "Degraded",
          not_configured: "Not configured",
          insufficient_data: "Insufficient data",
        },
        noRuntimeIssue: "None recorded",
        actionMessages: {
          applied: "Egress approval applied.",
          dry_run: "Egress approval dry run completed.",
          failed: "Egress approval failed.",
        },
        boundaries: {
          studio: {
            title: "Builder Studio tests",
            body: "Draft-agent test runs use the restricted OpenClaw path when configured.",
          },
          slash: {
            title: "Hub slash commands",
            body: "Runnable Hub agents cross this boundary before task and artifact output is stored.",
          },
          egress: {
            title: "Connector egress",
            body: "Approvals are scoped to one profile, host, port, access mode, reason, and expiry.",
          },
        },
      },
      adminAudit: {
        eyebrow: "Audit",
        title: "Audit",
        description:
          "Search the Console audit timeline. External sources, export, and retention controls remain dedicated follow-up surfaces.",
        searchLabel: "Search audit events",
        searchPlaceholder: "Actor, action, target, reason, metadata",
        searchButton: "Search",
        clearSearch: "Clear",
        generatedLabel: "Updated",
        sourcesTitle: "Sources",
        timelineTitle: "Timeline",
        selectedEvent: "Selected event",
        noEvents: "No audit events match this filter.",
        reason: "Reason",
        metadata: "Metadata",
        actor: "Actor",
        action: "Action",
        target: "Target",
        created: "Created",
        readOnlyNotice:
          "This page is read-only. Audit export, retention, and SIEM forwarding are not implemented in this slice.",
      },
      adminGovernance: {
        violations: {
          eyebrow: "Policies and guardrails",
          title: "Policy violations",
          description:
            "Review blocked or warned policy events from the last 24 hours. Policy authoring and enforcement producers remain separate admin work.",
          searchLabel: "Search policy violations",
          searchPlaceholder: "Actor, target, policy, severity, metadata",
          searchButton: "Search",
          clearSearch: "Clear",
          generatedLabel: "Updated",
          summaryTitle: "24h posture",
          tableTitle: "Violation log",
          empty: "No policy violations match this filter.",
          readOnlyNotice:
            "Policy edits stay outside this slice. Admins can acknowledge or resolve violation records with an audited note.",
          total: "Total",
          critical: "Critical",
          warning: "Warning",
          remediation: "Remediation",
          remediationHelp:
            "Add a short operator note. The original violation remains unchanged.",
          remediationNoteLabel: "Remediation note",
          remediationNotePlaceholder: "What was reviewed or fixed?",
          remediationStatus: "Remediation",
          acknowledge: "Acknowledge",
          resolve: "Resolve",
          statusOpen: "Open",
          statusAcknowledged: "Acknowledged",
          statusResolved: "Resolved",
          actionMessages: {
            acknowledged: "Policy violation acknowledged.",
            resolved: "Policy violation resolved.",
            failed:
              "Policy remediation failed. Check your Admin role and try again.",
          },
          policyType: "Policy",
          actionTaken: "Action",
          actor: "Actor",
          target: "Target",
          created: "Created",
          metadata: "Metadata",
          openAudit: "Open audit search",
        },
        pureMode: {
          eyebrow: "Sandbox governance",
          title: "Pure Mode",
          description:
            "Inspect the current Pure Mode posture, recent audit events, and typed admin transition control.",
          generatedLabel: "Updated",
          active: "Active",
          inactive: "Inactive",
          affectedComponents: "Affected components",
          noAffectedComponents: "No components are currently affected.",
          reason: "Reason",
          activatedBy: "Activated by",
          activatedAt: "Activated",
          deactivatedAt: "Deactivated",
          updatedAt: "State updated",
          controlTitle: "Typed confirmation",
          controlHelp:
            "Pure Mode transitions require Admin scope, a reason, an idempotency key, and the exact confirmation string.",
          confirmationLabel: "Confirmation",
          confirmationPlaceholder: "PURE",
          reasonLabel: "Reason",
          reasonPlaceholder: "Incident, support triage, or restore note",
          activateButton: "Activate Pure Mode",
          restoreButton: "Restore services",
          toggleUnavailable: "Control unavailable",
          historyTitle: "Recent Pure Mode events",
          noHistory: "No Pure Mode audit events are visible yet.",
          actionMessages: {
            activated: "Pure Mode activation recorded.",
            restored: "Pure Mode restore recorded.",
            failed:
              "Pure Mode transition failed. Check the confirmation, current state, and Admin role.",
          },
          readOnlyNotice:
            "Every activation or restore is written to audit with the confirming admin, reason, previous state, and affected scope.",
        },
        agentStudioQuota: {
          eyebrow: "Builder governance",
          title: "Agent Studio quota",
          description:
            "Control the daily test-run and token quota for Builder Agent Studio across the appliance.",
          generatedLabel: "Updated",
          policyTitle: "Current policy",
          controlTitle: "Quota control",
          source: "Source",
          status: "Status",
          runLimit: "Daily runs",
          tokenLimit: "Daily tokens",
          unlimited: "Unlimited",
          updatedBy: "Updated by",
          updatedAt: "Updated at",
          runLimitLabel: "Daily run limit",
          tokenLimitLabel: "Daily token limit",
          noteLabel: "Admin note",
          notePlaceholder: "Why is this quota being changed?",
          save: "Save quota policy",
          noOverride: "No admin override",
          actionMessages: {
            saved: "Agent Studio quota policy saved.",
            failed:
              "Quota policy update failed. Check the values and Admin role.",
          },
          help: "Leave a limit blank for unlimited. Changes apply to new Studio quota checks immediately.",
        },
      },
      notificationsDrawer: {
        title: "Notifications",
        triggerLabel: "Notifications",
        unreadBadge: (count: number) => `${count} unread`,
        unread: "unread",
        read: "Read",
        reading: "Reading...",
        markRead: "Mark read",
        readFailure: "Could not mark read. Try again.",
      },
      commandPalette: {
        label: "Command palette search",
        shortcut: "K",
        empty: "No permitted Hub results match this search.",
      },
      liveEvents: {
        ariaLabel: (status: string) => `Hub events ${status}`,
        connecting: "connecting",
        live: "live",
        offline: "offline",
      },
      metricLabels: {
        artifacts: "Artifacts",
        command: "Command",
        created: "Created",
        critical: "Critical",
        drafts: "Drafts",
        kind: "Kind",
        owner: "Owner",
        persona: "Persona",
        prompts: "Prompts",
        rejected: "Rejected",
        scope: "Scope",
        status: "Status",
        submitted: "Submitted",
        task: "Task",
        tokens: "Tokens",
        updated: "Updated",
        warnings: "Warnings",
      },
      usageSummary: {
        noTopModel: "No model activity",
        sourceStatusLabel: "Source status",
        topModelLabel: "Top model",
      },
      resourceCatalog: {
        eyebrow: "Hub catalog",
        title: "Resources",
        description:
          "Agents and vetted MCPs are runnable. Blueprints remain visible for planning but blocked until vetting, admin setup, and scoped egress are complete.",
        openDetails: "Open details",
      },
      resourceDetail: {
        eyebrow: "Resource detail",
        runtimePosture: "Runtime posture",
        allowedActions: "Allowed actions",
        mcpConnectorVetting: "MCP connector vetting",
        noRunAction: "No Hub run action is available for this resource.",
        open: "Open",
        unversioned: "Unversioned",
        unassigned: "Unassigned",
        notReviewed: "Not reviewed",
        none: "none",
        labels: {
          allowedEndpoints: "Allowed endpoints",
          auditEvents: "Audit events",
          checksum: "Checksum",
          dataClasses: "Data classes",
          lastReviewed: "Last reviewed",
          owner: "Owner",
          readWrite: "Read/write",
          requiredScopes: "Required scopes",
          runtimeProfile: "Runtime profile",
          secretsRequired: "Secrets required",
          sourceRef: "Source ref",
          sourceStatus: "Source status",
          tags: "Tags",
          type: "Type",
          version: "Version",
          vettingStatus: "Vetting status",
        },
      },
      tasksPage: {
        eyebrow: "Developer workbench",
        title: "Task Sessions",
        description:
          "Codex-like sessions for resumable work, logs, and outputs. Full authoring still belongs in Builder.",
        openSession: "Open session",
      },
      taskDetail: {
        eyebrow: "Task session",
        description:
          "Read-only workbench session status. Full editing and publishing remain in Builder.",
        sessionOutputs: "Session outputs",
        openArtifact: "Open artifact",
        noArtifacts: "This session has no inspectable artifacts yet.",
        context: "Context",
        openSource: "Open source",
        controlledRunOutput: "Controlled run output",
        noRunOutput:
          "No controlled run output has been attached to this session.",
        diffPreview: "Read-only diff preview",
        noDiffPreview: "No diff preview has been attached to this session.",
      },
      usagePage: {
        eyebrow: "Operational visibility",
        title: "Usage",
        description:
          "Usage is shown for capacity, adoption, and governance. It is not per-user billing.",
      },
      profilePage: {
        eyebrow: "Identity",
        title: "Profile",
        description:
          "Role comes from Keycloak. Capability overlays adjust Hub widgets and workbench access without bypassing server-side authorization.",
        effectiveAccess: "Effective access",
      },
      signIn: {
        eyebrow: "Secure console access",
        title: "Sign in",
        description:
          "Use the appliance identity provider to continue into the LLM Machines Console.",
        keycloak: "Sign in with Keycloak",
        footnote:
          "Your role and Hub capabilities are resolved from the Keycloak realm after sign-in.",
      },
      artifactsPage: {
        eyebrow: "Work outputs",
        title: "Artifacts",
        description:
          "Generated files, diffs, logs, and structured outputs stay inspectable without turning the Hub into a full IDE.",
        createdPrefix: "Created",
        openArtifact: "Open artifact",
      },
      artifactDetail: {
        eyebrow: "Artifact preview",
        description:
          "Read-only generated output. Hub previews artifacts; source edits stay in Builder.",
        preview: "Preview",
        detached: "Detached",
        openSourceTask: "Open source task",
      },
      resourceStates: {
        available: "Available",
        pending_vetting: "Pending vetting",
        blocked: "Blocked",
      },
      actionStates: {
        enabled: "enabled",
        blocked: "blocked",
      },
      severities: {
        critical: "critical",
        info: "info",
        warning: "warning",
      },
    },
  },
  surfaces: {
    hub: "Hub",
    builder: "Builder",
    admin: "Admin",
  },
  personas: {
    consumer: "Consumer",
    builder: "Builder",
    admin: "Admin",
  },
} as const
